services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_www:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - db_www:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    networks:
      - inception


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mafranco/data/mariadb
      o: bind

  db_www:
    driver: local
    driver_opts:
      type: none
      device: /home/mafranco/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
